dataset:
  name: celebahq
  input_dir: ../celebhq_256_subset
  image_size: 256
  file_ext: png
  max_images: 1000
  center_crop: false

model:
  name: hf_diffusers
  pretrained_id: google/ddpm-ema-celebahq-256
  use_fp16: false

task:
  name: inpainting

operator:
  name: random_box_mask
  box_h: 100
  box_w: 100
  mask_seed: 2025

sampler:
  name: ddnm

sampling:
  batch_size: 8
  num_inference_steps: 100
  eta: 0.85
  seed: 42

output:
  dir: outputs/celebahq_inpainting_randommask_ddnm_100