dataset:
  name: imagenet
  input_dir: ../ImageNet/imagenet_val_jpg
  image_size: 256
  file_ext: jpg
  max_images: 1000
  center_crop: true

model:
  name: openai_unet
  checkpoint: 256x256_diffusion_uncond.pt
  use_fp16: true

task:
  name: inpainting

operator:
  name: random_box_mask
  box_h: 100
  box_w: 100
  mask_seed: 2025

sampler:
  name: ddnm

sampling:
  batch_size: 8
  num_inference_steps: 100
  eta: 0.85
  seed: 42

output:
  dir: outputs/imagenet_inpainting_randommask_ddnm_100