dataset:
  name: imagenet
  input_dir: image_net/imagenet
  image_size: 256
  file_ext: jpg
  max_images: 1000
  center_crop: true

model:
  name: openai_unet
  checkpoint: 256x256_diffusion_uncond.pt
  use_fp16: true

task:
  name: superres

operator:
  name: mean_sr
  scale: 8

sampler:
  name: ddnm

sampling:
  batch_size: 8
  num_inference_steps: 200
  eta: 0.85
  seed: 42

output:
  dir: outputs/imagenet_superres_mean_ddnm
